#### Dataset params ###########################################################
dataset_name: hull
window: 64
window_lag: 1
horizon_lag: 1
stride: 1
test_len: 0.15
val_len: 0.1


#### Model params #############################################################
model_name: imputeformer
num_nodes: 94
input_dim: 3
output_dim: 1
input_embedding_dim: 96
learnable_embedding_dim: 32
feed_forward_dim: 256
num_temporal_heads: 4
num_layers: 4
dim_proj: 16
dropout: 0.1
f1_loss_weight: 0.01


#### Training params ##########################################################
batch_inference: 32
batch_size: 32
batches_epoch: 200
split_batch_in: 1
epochs: 150
patience: 20
precision: 32
prediction_loss_weight: 1.0
grad_clip_val: 5.0
l2_reg: 0.0
scale_target: true
loss_fn: l1_loss
lr: 0.001
lr_scheduler: magic
seed: 7
workers: 0
whiten_prob:
- 0.2
- 0.5
